version: '3.4'

services:
  smakownia.basket.api:
    image: ${DOCKER_REGISTRY-}smakowniabasketapi
    build:
      context: .
      dockerfile: src/Smakownia.Basket.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - default
      - smakownia
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD} --maxmemory 50mb --maxmemory-policy allkeys-lru'
    environment:
      - REDIS_PASSWORD=super-secret-password

networks:
  smakownia:
    name: smakownia
